proxy:
  title: Basic Shiny App
  landing-page: app/01_hello
  port: 8080
  authentication: simple
  admin-groups: admins
  users:
  - name: jack
    password: password
    groups: admins
  - name: tim
    password: password
  docker:
      internal-networking: true
  specs:
  - id: 01_hello
    display-name: Basic Shiny App
    description: Application which demonstrates the basics of a Shiny app
    container-cmd: ["/usr/bin/shiny-server.sh"] 
    container-image: thedatacollective/basic_shiny
    container-network: tdc-net

logging:
  file:
    shinyproxy.log
