version: "3.6"

services:
  nginx:
    image: nginx
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - shinyproxy
    networks:
      - tdc-net

  shinyproxy:
    build: ./shinyproxy
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock
      - ./shinyproxy-logs/server:/log
      - ./shinyproxy-logs/container:/container-logs
    ports:
      - 8080:8080
    networks:
      - tdc-net

networks:
  tdc-net:
    name: tdc-net

